version: 2

project_name: fuego

before:
  hooks:
    - go mod tidy

builds:
  - id: fuego
    main: ./cmd/fuego
    binary: fuego
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X github.com/abdul-hamid-achik/fuego/internal/version.Version={{.Version}}

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: abdul-hamid-achik
    name: fuego
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} v{{.Version}}"

brews:
  - name: fuego
    repository:
      owner: abdul-hamid-achik
      name: fuego-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    homepage: https://github.com/abdul-hamid-achik/fuego
    description: A file-system based Go framework for APIs and websites
    license: MIT
    install: |
      bin.install "fuego"
